name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      env:
        PYTHON_VERSION: 3.9
      ports:
        - 8080:80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs-material pillow

      - name: Build and deploy documentation
        run: mkdocs gh-deploy --force
