name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Update package lists
        run: apt-get update

      - name: Install Git
        run: apt-get install git -y

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pillow cairosvg

      - name: Check if directory is a Git repository
        run: |
          if [ -d .git ]; then
            echo "Directory is a Git repository"
          else
            echo "Directory is NOT a Git repository"
            rm -rf *  # Remove existing content
            git clone https://github.com/ltomasevic/mkdocs.git .
          fi

      - name: Configure Git for deployment
        run: |
          git config --global --add safe.directory /__w/mkdocs/mkdocs

      - name: Build and deploy documentation
        run: mkdocs gh-deploy --force
