name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Git
        run: sudo apt-get install git -y

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material pillow cairosvg

      - name: Configure Git for deployment
        run: |
          git config --global --add safe.directory /__w/mkdocs/mkdocs

      - name: Build and deploy documentation
        run: mkdocs gh-deploy --force
